# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
gems:                [jekyll-paginate]
title:               Felipe Lalanne
tagline:             'An about page'
description:         'I&apos;m an R&D engineer, software developer, bicycle enthusiast and tv, food and movie lover. This is my personal website.'
url:                 https://felipe.lalanne.cl
baseurl:             ''
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Felipe Lalanne
  url:               https://twitter.com/pipex
  email:             felipe@lalanne.cl
  github:            https://github.com/pipex
  linkedin:          https://cl.linkedin.com/in/flalanne
  twitter:           pipex


# Custom vars
version:             1.0.0
